package com.yotfr.weather.presentation.sevendaysforecast

import androidx.annotation.DrawableRes
import com.yotfr.weather.domain.model.HourlyWeatherData

data class SevenDaysForecastState(
    val isLoading: Boolean = false,
    val selectedDate: String? = null,
    val toolbarTitle: String = "",
    val selectedMaxTemperature: String = "",
    val selectedMinTemperature: String = "",
    @DrawableRes val selectedWeatherType: Int? = null,
    val sunriseTime: String? = null,
    val sunsetTime: String? = null,
    val selectedDayHourlyWeatherList: List<HourlyWeatherData>? = emptyList(),
    val todayDate: String? = null,
    val todayMaxTemperature: String = "",
    val todayMinTemperature: String = "",
    @DrawableRes val todayWeatherType: Int? = null,
    val tomorrowDate: String? = null,
    val tomorrowMaxTemperature: String = "",
    val tomorrowMinTemperature: String = "",
    @DrawableRes val tomorrowWeatherType: Int? = null,
    val afterTomorrowDate: String? = null,
    val afterTomorrowMaxTemperature: String = "",
    val afterTomorrowMinTemperature: String = "",
    val afterTomorrowDayOfWeek: String = "",
    @DrawableRes val afterTomorrowWeatherType: Int? = null,
    val inTwoDaysDate: String? = null,
    val inTwoDaysMaxTemperature: String = "",
    val inTwoDaysMinTemperature: String = "",
    val inTwoDaysDayOfWeek: String = "",
    @DrawableRes val inTwoDaysWeatherType: Int? = null,
    val inThreeDaysDate: String? = null,
    val inThreeDaysMaxTemperature: String = "",
    val inThreeDaysMinTemperature: String = "",
    val inThreeDaysDayOfWeek: String = "",
    @DrawableRes val inThreeDaysWeatherType: Int? = null,
    val inFourDaysDate: String? = null,
    val inFourDaysMaxTemperature: String = "",
    val inFourDaysMinTemperature: String = "",
    val inFourDaysDayOfWeek: String = "",
    @DrawableRes val inFourDaysWeatherType: Int? = null,
    val inFiveDaysDate: String? = null,
    val inFiveDaysMaxTemperature: String = "",
    val inFiveDaysMinTemperature: String = "",
    val inFiveDaysDayOfWeek: String = "",
    @DrawableRes val inFiveDaysWeatherType: Int? = null
)
